[package]
edition = "2024"
name = "shrubbery"
version = "0.1.2"
license = "MIT"
keywords = ["shrubbery", "behavior-tree", "ai"]
documentation = "https://docs.rs/shrubbery"
homepage = "https://github.com/thomasMilesTgm/shrubbery"
repository = "https://github.com/thomasMilesTgm/shrubbery"
readme = "README.md"
description = "Composable Berhavior Trees"

[dependencies]
ahash = "0.8.3"
derive_more = { version = "0.99.17", default-features = false, features = [
  "deref",
  "deref_mut",
  "as_mut",
  "as_ref",
  "from",
  "try_into",
] }
graphviz-rust = "0.9.0"
log = "0.4.21"
regex = "1.8.4"
thiserror = "1.0.40"
